# Generated by Django 5.1.5 on 2025-01-15 12:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApplicationType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="Названия заявки"),
                ),
            ],
            options={
                "verbose_name": "Типы заявок",
                "verbose_name_plural": "Типы заявок",
            },
        ),
        migrations.CreateModel(
            name="Pattern",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250, verbose_name="Наименования шаблона"
                    ),
                ),
                ("activity", models.BooleanField(verbose_name="Активность шаблона")),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Премечания заявки"),
                ),
                ("pattern", models.JSONField(blank=True, verbose_name="Шаблон заявки")),
                (
                    "application_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="template_service.applicationtype",
                        verbose_name="Тип заявки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон",
                "verbose_name_plural": "Шаблоны",
            },
        ),
    ]
